baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Graus de Liberdade'

google_analytics_id: "G-RFMHFLDVB1"
homepage:
  show_call_box: false
logo:
  mobile: "images/home.svg"
  desktop: "images/home.svg"
  desktop_height: "32px"
footer:
  # copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Graus de Liberdade"
  meta_og_type: "website"
  meta_og_url: "https://grausdeliberdade.pt"
  meta_og_image: "images/illustrations/graus.png"
  meta_og_description: "Graus de Liberdade - Psicoterapia e Neuropsicologia"
  # meta_twitter_card: "summary"
  # meta_twitter_site: "@zerostaticio"
  # meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
